spring:
  application:
    name: Supermarket_System

  datasource:
    url: jdbc:mysql://localhost:3306/supermarketdb
    username: root
    password: dumbPassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#   DISABLE EUREKA FOR NOW
    register-with-eureka: false
    fetch-registry: false